sudo: required
services:
  - docker

env:
  global:
    - GREP_TIMEOUT=360

before_install:
  - sudo apt-get update
  - sudo apt-get install -qy -o Dpkg::Options::="--force-confold" docker-ce coreutils
  - sudo apt-get install -y zlib1g-dev

script:
  # Bring up the postgres, redis, and app containers
  - docker-compose up --build -d

  - timeout $GREP_TIMEOUT grep -m 1 'Running migrations' <(docker-compose logs --follow app 2>&1)
  - timeout $GREP_TIMEOUT grep -m 1 'spawned uWSGI http 1' <(docker-compose logs --follow app 2>&1)
  - docker-compose run app /venv/bin/python /code/manage.py check

after_script:
  - docker-compose logs
  - docker images
