defaultEntryPoints = ["http"]

[entryPoints]
    [entryPoints.http]
    address = ":80"

[web]
address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
exposedbydefault = false
watch = true